# Generated by Django 4.1.2 on 2022-11-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pointing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiant", name="etudiantNomComplet", field=models.TextField(),
        ),
    ]
