# Generated by Django 4.1.3 on 2022-11-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='enseignantCode',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='etudiantMatricule',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='matiereCode',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='niveauCode',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='parcoursCode',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
