# Generated by Django 4.1.3 on 2022-11-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneeuniv',
            name='anneeEncours',
            field=models.BooleanField(default=False),
        ),
    ]
