# Generated by Django 4.1.3 on 2022-11-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointing', '0002_alter_enseignant_enseignantcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='matiereCode',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
