# Generated by Django 4.1.3 on 2022-12-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointing', '0003_eventlog_etudiant_eventlog_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
