# Generated by Django 4.1.3 on 2022-12-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointing', '0005_remove_eventlog_etudiant_remove_eventlog_matiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlog',
            name='saved',
        ),
    ]
