# Generated by Django 4.1.3 on 2022-12-03 05:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pointing', '0006_remove_eventlog_saved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointageId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime', models.DateTimeField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('pointageIn', models.BooleanField()),
                ('pointageOut', models.BooleanField()),
                ('etudiant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pointing.etudiant')),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pointing.matiere')),
            ],
        ),
    ]
