# Generated by Django 4.1.3 on 2022-12-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointing', '0007_pointage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='pointage',
            name='time',
        ),
    ]
