# Generated by Django 4.1.3 on 2022-12-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointing', '0008_remove_pointage_date_remove_pointage_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointage',
            name='datetime',
        ),
        migrations.AddField(
            model_name='pointage',
            name='datetimeDebut',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pointage',
            name='datetimeFin',
            field=models.DateTimeField(null=True),
        ),
    ]
