# Generated by Django 4.1.3 on 2022-12-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointing', '0009_remove_pointage_datetime_pointage_datetimedebut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='direction',
            field=models.CharField(default='UKN', max_length=255),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='pointageIn',
            field=models.CharField(default='UKN', max_length=3),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='pointageOut',
            field=models.CharField(default='UKN', max_length=3),
        ),
    ]
