# Generated by Django 4.1.3 on 2022-12-05 12:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pointing', '0010_alter_eventlog_direction_alter_pointage_pointagein_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointage',
            name='id',
        ),
        migrations.AlterField(
            model_name='pointage',
            name='pointageId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
