# Generated by Django 4.1.3 on 2022-12-05 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointing', '0011_remove_pointage_id_alter_pointage_pointageid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pointage',
        ),
    ]
