# Generated by Django 4.1.3 on 2022-12-05 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointing', '0012_delete_pointage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetimeDebut', models.DateTimeField(null=True)),
                ('datetimeFin', models.DateTimeField(null=True)),
                ('pointageIn', models.CharField(default='UKN', max_length=3)),
                ('pointageOut', models.CharField(default='UKN', max_length=3)),
                ('etudiant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pointing.etudiant')),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pointing.matiere')),
            ],
        ),
    ]
